create extension if not exists pgcrypto with schema extensions;

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  video_id text not null,
  bucket text not null,
  file_path text not null,
  has_lesion boolean not null default false,
  lesion_onset_sec numeric(10, 3),
  is_test boolean not null default true,
  session_pool integer check (session_pool between 1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.videos
  add column if not exists has_lesion boolean not null default false,
  add column if not exists lesion_onset_sec numeric(10, 3),
  add column if not exists is_test boolean not null default true,
  add column if not exists session_pool integer;

create unique index if not exists videos_video_id_key
  on public.videos (video_id);

create index if not exists videos_study_mode_pool_idx
  on public.videos (is_test, session_pool, video_id);

create table if not exists public.assessment_queue (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_number integer not null check (session_number between 1 and 3),
  video_id text not null references public.videos (video_id),
  video_order integer not null check (video_order >= 1),
  created_at timestamptz not null default now()
);

create unique index if not exists assessment_queue_session_order_idx
  on public.assessment_queue (participant_id, session_number, video_order);

create unique index if not exists assessment_queue_session_video_idx
  on public.assessment_queue (participant_id, session_number, video_id);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_number integer not null check (session_number between 1 and 3),
  video_id text not null references public.videos (video_id),
  video_order integer not null check (video_order >= 1),
  answer boolean not null,
  correct boolean not null,
  response_type text not null check (
    response_type in ('lesion_detected', 'no_lesion_detected')
  ),
  response_time_ms integer not null check (response_time_ms >= 0),
  video_time_at_click numeric(10, 3),
  detection_latency_ms integer,
  video_completed boolean not null default false,
  no_response_latency_ms bigint check (
    no_response_latency_ms is null
    or no_response_latency_ms >= 0
  ),
  created_at timestamptz not null default now()
);

alter table public.responses
  add column if not exists participant_id text,
  add column if not exists session_number integer,
  add column if not exists video_order integer,
  add column if not exists correct boolean,
  add column if not exists response_type text,
  add column if not exists video_time_at_click numeric(10, 3),
  add column if not exists detection_latency_ms integer,
  add column if not exists video_completed boolean not null default false,
  add column if not exists no_response_latency_ms bigint;

create index if not exists responses_participant_session_order_idx
  on public.responses (participant_id, session_number, video_order);

create unique index if not exists responses_unique_trial
  on public.responses (participant_id, session_number, video_id, video_order);

create table if not exists public.lesion_detection_events (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_number integer not null
    check (session_number between 1 and 3),
  video_id text not null references public.videos (video_id),
  video_order integer not null check (video_order >= 1),
  click_index integer not null check (click_index >= 1),
  video_time_at_click double precision not null
    check (video_time_at_click >= 0),
  response_time_ms bigint not null check (response_time_ms >= 0),
  lesion_onset_sec double precision,
  detection_latency_ms bigint,
  overridden boolean not null,
  final_valid boolean not null,
  created_at timestamptz not null default now(),
  constraint lesion_detection_events_unique_click
    unique (participant_id, session_number, video_id, click_index),
  constraint lesion_detection_events_validity_pair
    check (final_valid <> overridden)
);

create index if not exists lesion_detection_events_audit_order_idx
  on public.lesion_detection_events (
    participant_id,
    session_number,
    video_order,
    click_index
  );

create index if not exists lesion_detection_events_final_analysis_idx
  on public.lesion_detection_events (
    video_id,
    detection_latency_ms
  )
  where final_valid = true;

alter table public.videos enable row level security;
alter table public.assessment_queue enable row level security;
alter table public.responses enable row level security;
alter table public.lesion_detection_events enable row level security;

drop policy if exists "Allow anonymous V001 video lookup" on public.videos;
drop policy if exists "Allow anonymous videos lookup" on public.videos;
drop policy if exists "Allow anonymous assessment queue lookup" on public.assessment_queue;
drop policy if exists "Allow anonymous assessment queue inserts" on public.assessment_queue;
drop policy if exists "Allow anonymous queue insert" on public.assessment_queue;
drop policy if exists "Allow anonymous queue read" on public.assessment_queue;
drop policy if exists "Allow anonymous read of video metadata" on public.videos;

drop policy if exists "Allow anonymous response inserts"
  on public.responses;

drop policy if exists "Allow anonymous lesion event inserts"
  on public.lesion_detection_events;

-- Direct writes are revoked; only the trusted SECURITY DEFINER RPC may write.
revoke all on table public.lesion_detection_events
  from public, anon, authenticated;
revoke all on sequence public.lesion_detection_events_id_seq
  from public, anon, authenticated;
revoke all on table public.responses
  from public, anon, authenticated;
revoke all on sequence public.responses_id_seq
  from public, anon, authenticated;

create or replace function public.get_next_video_order(
  p_participant_id text,
  p_session_number integer
)
returns integer
language sql
security definer
set search_path = public
as $$
  with queued as (
    select q.video_id, q.video_order
    from public.assessment_queue q
    where q.participant_id = p_participant_id
      and q.session_number = p_session_number
  )
  select coalesce(
    (
      select min(q.video_order)
      from queued q
      where not exists (
        select 1
        from public.responses r
        where r.participant_id = p_participant_id
          and r.session_number = p_session_number
          and r.video_id = q.video_id
          and r.video_order = q.video_order
      )
    ),
    (
      select count(*)::integer + 1
      from queued
    )
  );
$$;

grant execute on function public.get_next_video_order(text, integer) to anon;

-- The trusted migration owner, not anon, performs the validated table writes.
create or replace function public.submit_video_response(
  p_participant_id text,
  p_session_number integer,
  p_video_id text,
  p_video_order integer,
  p_answer boolean,
  p_response_time_ms bigint,
  p_no_response_latency_ms bigint,
  p_video_completed boolean,
  p_clicks jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  video_has_lesion boolean;
  video_lesion_onset_sec double precision;
  click_count integer;
  distinct_click_count integer;
  minimum_click_index integer;
  maximum_click_index integer;
  first_video_time double precision;
  first_response_time_ms bigint;
  first_detection_latency_ms bigint;
begin
  if pg_catalog.length(pg_catalog.btrim(coalesce(p_participant_id, ''))) = 0 then
    raise exception 'participant_id is required';
  end if;

  if p_session_number is null
     or p_session_number not between 1 and 3 then
    raise exception 'session_number must be 1, 2, or 3';
  end if;

  if p_video_order is null or p_video_order < 1 then
    raise exception 'video_order must be positive';
  end if;

  if p_answer is null then
    raise exception 'answer is required';
  end if;

  if p_video_completed is distinct from true then
    raise exception 'video must be completed before submission';
  end if;

  if p_response_time_ms is null or p_response_time_ms < 0 then
    raise exception 'response_time_ms must be non-negative';
  end if;

  if p_answer is true and p_no_response_latency_ms is not null then
    raise exception 'positive responses cannot have no_response_latency_ms';
  end if;

  if p_answer is false and (
    p_no_response_latency_ms is null
    or p_no_response_latency_ms < 0
  ) then
    raise exception 'negative responses require no_response_latency_ms';
  end if;

  if p_clicks is null or pg_catalog.jsonb_typeof(p_clicks) <> 'array' then
    raise exception 'p_clicks must be a JSON array';
  end if;

  select v.has_lesion, v.lesion_onset_sec
  into video_has_lesion, video_lesion_onset_sec
  from public.assessment_queue q
  join public.videos v on v.video_id = q.video_id
  where q.participant_id = p_participant_id
    and q.session_number = p_session_number
    and q.video_id = p_video_id
    and q.video_order = p_video_order;

  if not found then
    raise exception 'assessment queue item does not exist';
  end if;

  if video_has_lesion is null then
    raise exception 'videos.has_lesion is required';
  end if;

  select
    pg_catalog.count(*)::integer,
    pg_catalog.count(distinct click_row.click_index)::integer,
    pg_catalog.min(click_row.click_index),
    pg_catalog.max(click_row.click_index)
  into
    click_count,
    distinct_click_count,
    minimum_click_index,
    maximum_click_index
  from pg_catalog.jsonb_to_recordset(p_clicks) as click_row(
    click_index integer,
    video_time_at_click double precision,
    response_time_ms bigint
  );

  if p_answer is true and click_count = 0 then
    raise exception 'positive responses require at least one lesion click';
  end if;

  if click_count > 0 and (
    distinct_click_count <> click_count
    or minimum_click_index <> 1
    or maximum_click_index <> click_count
  ) then
    raise exception 'click indexes must be unique and contiguous from 1';
  end if;

  if exists (
    select 1
    from pg_catalog.jsonb_to_recordset(p_clicks) as click_row(
      click_index integer,
      video_time_at_click double precision,
      response_time_ms bigint
    )
    where click_row.click_index is null
      or click_row.video_time_at_click is null
      or click_row.video_time_at_click < 0
      or click_row.response_time_ms is null
      or click_row.response_time_ms < 0
  ) then
    raise exception 'click timing values are invalid';
  end if;

  if p_answer is true then
    select
      pg_catalog.round(click_row.video_time_at_click::numeric, 3)::double precision,
      click_row.response_time_ms,
      case
        when video_lesion_onset_sec is null then null
        else pg_catalog.round(
          (
            pg_catalog.round(click_row.video_time_at_click::numeric, 3)::double precision
            - video_lesion_onset_sec
          ) * 1000
        )::bigint
      end
    into
      first_video_time,
      first_response_time_ms,
      first_detection_latency_ms
    from pg_catalog.jsonb_to_recordset(p_clicks) as click_row(
      click_index integer,
      video_time_at_click double precision,
      response_time_ms bigint
    )
    order by click_row.click_index
    limit 1;
  end if;

  insert into public.lesion_detection_events (
    participant_id,
    session_number,
    video_id,
    video_order,
    click_index,
    video_time_at_click,
    response_time_ms,
    lesion_onset_sec,
    detection_latency_ms,
    overridden,
    final_valid
  )
  select
    p_participant_id,
    p_session_number,
    p_video_id,
    p_video_order,
    click_row.click_index,
    pg_catalog.round(click_row.video_time_at_click::numeric, 3)::double precision,
    click_row.response_time_ms,
    video_lesion_onset_sec,
    case
      when video_lesion_onset_sec is null then null
      else pg_catalog.round(
        (
          pg_catalog.round(click_row.video_time_at_click::numeric, 3)::double precision
          - video_lesion_onset_sec
        ) * 1000
      )::bigint
    end,
    not p_answer,
    p_answer
  from pg_catalog.jsonb_to_recordset(p_clicks) as click_row(
    click_index integer,
    video_time_at_click double precision,
    response_time_ms bigint
  );

  insert into public.responses (
    participant_id,
    session_number,
    video_id,
    video_order,
    answer,
    correct,
    response_time_ms,
    video_time_at_click,
    detection_latency_ms,
    response_type,
    video_completed,
    no_response_latency_ms
  )
  values (
    p_participant_id,
    p_session_number,
    p_video_id,
    p_video_order,
    p_answer,
    video_has_lesion = p_answer,
    case
      when p_answer then first_response_time_ms
      else p_response_time_ms
    end,
    case when p_answer then first_video_time else null end,
    case when p_answer then first_detection_latency_ms else null end,
    case
      when p_answer then 'lesion_detected'
      else 'no_lesion_detected'
    end,
    true,
    case when p_answer then null else p_no_response_latency_ms end
  );
end
$$;

revoke all on function public.submit_video_response(
  text,
  integer,
  text,
  integer,
  boolean,
  bigint,
  bigint,
  boolean,
  jsonb
) from public;

revoke all on function public.submit_video_response(
  text,
  integer,
  text,
  integer,
  boolean,
  bigint,
  bigint,
  boolean,
  jsonb
) from authenticated;

grant execute on function public.submit_video_response(
  text,
  integer,
  text,
  integer,
  boolean,
  bigint,
  bigint,
  boolean,
  jsonb
) to anon;

comment on function public.submit_video_response(
  text,
  integer,
  text,
  integer,
  boolean,
  bigint,
  bigint,
  boolean,
  jsonb
) is 'SECURITY DEFINER is intentional: response and event tables revoke direct public, anon, and authenticated writes so this validated RPC is the only write boundary.';

insert into storage.buckets (id, name, public)
values ('SSL', 'SSL', false)
on conflict (id) do update set public = false;

drop policy if exists "Allow anonymous V001 signed URL reads"
  on storage.objects;

drop policy if exists "Allow anonymous V001 video reads"
  on storage.objects;

drop policy if exists "Allow anonymous signed URL reads for video objects"
  on storage.objects;

create policy "Allow anonymous signed URL reads for video objects"
  on storage.objects
  for select
  to anon
  using (
    bucket_id = 'SSL'
    and exists (
      select 1
      from public.videos v
      where v.bucket = storage.objects.bucket_id
        and v.file_path = storage.objects.name
      )
  );

-- Canonical fresh-install form of session_access_hardening.sql.

create table if not exists public.assessment_runtime_config (
  id integer primary key check (id = 1),
  study_mode text not null check (study_mode in ('dev', 'formal')),
  updated_at timestamptz not null default now()
);

insert into public.assessment_runtime_config (id, study_mode)
values (1, 'dev')
on conflict (id) do nothing;

alter table public.assessment_runtime_config enable row level security;

create table if not exists public.assessment_session_access (
  participant_id text not null,
  session_number integer not null check (session_number between 1 and 3),
  access_token_digest bytea not null check (pg_catalog.octet_length(access_token_digest) = 32),
  created_at timestamptz not null default now(),
  primary key (participant_id, session_number)
);
alter table public.assessment_session_access enable row level security;

revoke all on table public.assessment_runtime_config from public, anon, authenticated;
revoke all on table public.assessment_session_access from public, anon, authenticated;
revoke all on table public.assessment_queue from public, anon, authenticated;
revoke all on sequence public.assessment_queue_id_seq from public, anon, authenticated;
revoke all on table public.videos from public, anon, authenticated;
drop policy if exists "Allow anonymous videos lookup" on public.videos;
drop policy if exists "Allow anonymous assessment queue lookup" on public.assessment_queue;
drop policy if exists "Allow anonymous assessment queue inserts" on public.assessment_queue;
drop policy if exists "Allow anonymous queue insert" on public.assessment_queue;
drop policy if exists "Allow anonymous queue read" on public.assessment_queue;
drop policy if exists "Allow anonymous read of video metadata" on public.videos;
revoke all on function public.get_next_video_order(text, integer) from public, anon, authenticated;

create or replace function public.can_read_assessment_video_object(p_bucket text, p_object_name text)
returns boolean
language sql security definer set search_path = ''
as $$
  select exists (
    select 1 from public.videos v
    where v.bucket = p_bucket and v.file_path = p_object_name
  );
$$;
revoke all on function public.can_read_assessment_video_object(text, text) from public, authenticated;
grant execute on function public.can_read_assessment_video_object(text, text) to anon;
drop policy if exists "Allow anonymous signed URL reads for video objects" on storage.objects;
create policy "Allow anonymous signed URL reads for video objects"
  on storage.objects for select to anon
  using (public.can_read_assessment_video_object(bucket_id, name));

drop function if exists public.start_or_resume_assessment(text, integer, text, text);

create or replace function public.start_or_resume_assessment(
  p_participant_id text, p_session_number integer, p_access_token text
)
returns table (
  video_id text, video_order integer, bucket text, file_path text,
  next_video_order integer, queue_length integer, study_mode text
)
language plpgsql security definer set search_path = ''
as $$
declare
  token_digest bytea;
  stored_digest bytea;
  normalized_mode text;
  existing_queue_length integer;
  legacy_queue_matches_mode boolean;
  eligible_video_count integer;
  resolved_next_video_order integer;
begin
  if pg_catalog.length(pg_catalog.btrim(coalesce(p_participant_id, ''))) = 0 then
    raise exception 'participant_id is required';
  end if;
  if p_session_number is null or p_session_number not between 1 and 3 then
    raise exception 'session_number must be 1, 2, or 3';
  end if;
  if pg_catalog.length(coalesce(p_access_token, '')) < 32 then
    raise exception 'assessment access token is invalid';
  end if;
  select c.study_mode into normalized_mode
  from public.assessment_runtime_config c
  where c.id = 1;
  if not found then
    raise exception 'assessment runtime configuration is missing';
  end if;
  token_digest := extensions.digest(p_access_token, 'sha256');
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_participant_id || ':' || p_session_number::text, 0)
  );
  select access_token_digest into stored_digest
  from public.assessment_session_access
  where participant_id = p_participant_id and session_number = p_session_number;
  if found then
    if stored_digest is distinct from token_digest then
      raise exception 'assessment access token is invalid';
    end if;
  else
    select pg_catalog.count(*)::integer into existing_queue_length
    from public.assessment_queue
    where participant_id = p_participant_id and session_number = p_session_number;
    if existing_queue_length > 0 then
      select not exists (
        select 1
        from public.assessment_queue q
        join public.videos v on v.video_id = q.video_id
        where q.participant_id = p_participant_id
          and q.session_number = p_session_number
          and (
            case
              when normalized_mode = 'dev' then v.is_test is true
              else v.is_test is false and v.session_pool = p_session_number
            end
          ) is not true
      ) into legacy_queue_matches_mode;
      if legacy_queue_matches_mode is not true then
        raise exception 'legacy queue does not match configured study mode';
      end if;
    end if;
    insert into public.assessment_session_access(participant_id, session_number, access_token_digest)
    values (p_participant_id, p_session_number, token_digest);
  end if;
  select pg_catalog.count(*)::integer into existing_queue_length
  from public.assessment_queue
  where participant_id = p_participant_id and session_number = p_session_number;
  if existing_queue_length = 0 then
    select pg_catalog.count(*)::integer into eligible_video_count
    from public.videos v
    where (normalized_mode = 'dev' and v.is_test is true)
      or (normalized_mode = 'formal' and v.is_test is false and v.session_pool = p_session_number);
    if normalized_mode = 'formal' and eligible_video_count <> 40 then
      raise exception using message = pg_catalog.format(
        'Session %s is not ready: %s/40 formal videos configured.', p_session_number, eligible_video_count
      );
    end if;
    if normalized_mode = 'dev' and eligible_video_count = 0 then
      raise exception 'No development videos are configured.';
    end if;
    insert into public.assessment_queue(participant_id, session_number, video_id, video_order)
    select p_participant_id, p_session_number, v.video_id,
      pg_catalog.row_number() over (order by pg_catalog.random())::integer
    from public.videos v
    where (normalized_mode = 'dev' and v.is_test is true)
      or (normalized_mode = 'formal' and v.is_test is false and v.session_pool = p_session_number);
  end if;
  select pg_catalog.count(*)::integer into existing_queue_length
  from public.assessment_queue
  where participant_id = p_participant_id and session_number = p_session_number;
  select coalesce((
    select pg_catalog.min(q.video_order) from public.assessment_queue q
    where q.participant_id = p_participant_id and q.session_number = p_session_number
      and not exists (
        select 1 from public.responses r where r.participant_id = q.participant_id
          and r.session_number = q.session_number and r.video_id = q.video_id and r.video_order = q.video_order
      )
  ), existing_queue_length + 1) into resolved_next_video_order;
  return query
  select q.video_id, q.video_order, v.bucket, v.file_path, resolved_next_video_order, existing_queue_length, normalized_mode
  from public.assessment_queue q join public.videos v on v.video_id = q.video_id
  where q.participant_id = p_participant_id and q.session_number = p_session_number
  order by q.video_order;
end
$$;

-- The old nine-argument function remains an owner-only internal writer.
revoke all on function public.submit_video_response(text, integer, text, integer, boolean, bigint, bigint, boolean, jsonb)
  from public, anon, authenticated;

create or replace function public.submit_video_response(
  p_participant_id text,
  p_session_number integer,
  p_video_id text,
  p_video_order integer,
  p_answer boolean,
  p_response_time_ms bigint,
  p_no_response_latency_ms bigint,
  p_video_completed boolean,
  p_clicks jsonb,
  p_access_token text
)
returns void
language plpgsql security definer set search_path = ''
as $$
declare
  token_digest bytea;
  stored_digest bytea;
  has_lesion boolean;
  onset_sec double precision;
  first_time double precision;
  first_response_time_ms bigint;
  first_latency bigint;
  current_order integer;
  existing public.responses%rowtype;
  expected_events jsonb;
  stored_events jsonb;
  click_count integer;
begin
  if pg_catalog.length(pg_catalog.btrim(coalesce(p_participant_id, ''))) = 0 then raise exception 'participant_id is required'; end if;
  if p_session_number is null or p_session_number not between 1 and 3 then raise exception 'session_number must be 1, 2, or 3'; end if;
  if pg_catalog.length(coalesce(p_access_token, '')) < 32 then raise exception 'assessment access token is invalid'; end if;
  if p_video_order is null or p_video_order < 1 then raise exception 'video_order must be positive'; end if;
  if p_answer is null then raise exception 'answer is required'; end if;
  if p_video_completed is distinct from true then raise exception 'video must be completed before submission'; end if;
  if p_response_time_ms is null or p_response_time_ms < 0 then raise exception 'response_time_ms must be non-negative'; end if;
  if p_answer and p_no_response_latency_ms is not null then raise exception 'positive responses cannot have no_response_latency_ms'; end if;
  if not p_answer and (p_no_response_latency_ms is null or p_no_response_latency_ms < 0) then raise exception 'negative responses require no_response_latency_ms'; end if;
  if p_clicks is null or pg_catalog.jsonb_typeof(p_clicks) <> 'array' then raise exception 'p_clicks must be a JSON array'; end if;
  token_digest := extensions.digest(p_access_token, 'sha256');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_participant_id || ':' || p_session_number::text, 0));
  select access_token_digest into stored_digest from public.assessment_session_access
  where participant_id = p_participant_id and session_number = p_session_number;
  if not found or stored_digest is distinct from token_digest then raise exception 'assessment access token is invalid'; end if;
  select v.has_lesion, v.lesion_onset_sec into has_lesion, onset_sec
  from public.assessment_queue q join public.videos v on v.video_id = q.video_id
  where q.participant_id = p_participant_id and q.session_number = p_session_number
    and q.video_id = p_video_id and q.video_order = p_video_order;
  if not found then raise exception 'assessment queue item does not exist'; end if;
  select pg_catalog.count(*)::integer into click_count from pg_catalog.jsonb_to_recordset(p_clicks) as c(click_index integer, video_time_at_click double precision, response_time_ms bigint);
  if p_answer and click_count = 0 then raise exception 'positive responses require at least one lesion click'; end if;
  if exists (
    select 1 from pg_catalog.jsonb_to_recordset(p_clicks) as c(click_index integer, video_time_at_click double precision, response_time_ms bigint)
    where c.click_index is null or c.click_index < 1 or c.video_time_at_click is null or c.video_time_at_click < 0 or c.response_time_ms is null or c.response_time_ms < 0
  ) then raise exception 'click timing values are invalid'; end if;
  if click_count > 0 and exists (
    select 1 from (
      select c.click_index, pg_catalog.row_number() over (order by c.click_index) as expected_index
      from pg_catalog.jsonb_to_recordset(p_clicks) as c(click_index integer, video_time_at_click double precision, response_time_ms bigint)
    ) checked where click_index <> expected_index
  ) then raise exception 'click indexes must be unique and contiguous from 1'; end if;
  if p_answer is true then
    select pg_catalog.round(c.video_time_at_click::numeric, 3)::double precision, c.response_time_ms,
      case when onset_sec is null then null else pg_catalog.round((pg_catalog.round(c.video_time_at_click::numeric, 3)::double precision - onset_sec) * 1000)::bigint end
    into first_time, first_response_time_ms, first_latency
    from pg_catalog.jsonb_to_recordset(p_clicks) as c(click_index integer, video_time_at_click double precision, response_time_ms bigint)
    order by c.click_index limit 1;

    if p_answer is true and p_response_time_ms <> first_response_time_ms then
      raise exception 'positive response_time_ms must equal the first lesion click response_time_ms';
    end if;
  end if;
  select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_array(c.click_index, pg_catalog.round(c.video_time_at_click::numeric, 3)::double precision, c.response_time_ms, onset_sec,
    case when onset_sec is null then null else pg_catalog.round((pg_catalog.round(c.video_time_at_click::numeric, 3)::double precision - onset_sec) * 1000)::bigint end, not p_answer, p_answer) order by c.click_index), '[]'::jsonb)
  into expected_events from pg_catalog.jsonb_to_recordset(p_clicks) as c(click_index integer, video_time_at_click double precision, response_time_ms bigint);
  select r.* into existing from public.responses r where r.participant_id = p_participant_id and r.session_number = p_session_number and r.video_id = p_video_id and r.video_order = p_video_order;
  if found then
    select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_array(e.click_index, e.video_time_at_click, e.response_time_ms, e.lesion_onset_sec, e.detection_latency_ms, e.overridden, e.final_valid) order by e.click_index), '[]'::jsonb)
    into stored_events from public.lesion_detection_events e where e.participant_id = p_participant_id and e.session_number = p_session_number and e.video_id = p_video_id and e.video_order = p_video_order;
    -- An idempotent replay returns success only for the exact committed payload.
    if existing.answer = p_answer and existing.correct = (has_lesion = p_answer)
      and existing.response_time_ms = p_response_time_ms
      and existing.video_time_at_click is not distinct from case when p_answer then first_time else null end
      and existing.detection_latency_ms is not distinct from case when p_answer then first_latency else null end
      and existing.response_type = case when p_answer then 'lesion_detected' else 'no_lesion_detected' end
      and existing.video_completed is true
      and existing.no_response_latency_ms is not distinct from case when p_answer then null else p_no_response_latency_ms end
      and stored_events = expected_events then return; end if;
    raise exception 'existing response differs from retry payload';
  end if;
  -- New submissions may only write the first unanswered queue order.
  select pg_catalog.min(q.video_order) into current_order from public.assessment_queue q
  where q.participant_id = p_participant_id and q.session_number = p_session_number and not exists (
    select 1 from public.responses r where r.participant_id = q.participant_id and r.session_number = q.session_number and r.video_id = q.video_id and r.video_order = q.video_order
  );
  if current_order is null then raise exception 'assessment session is already complete'; end if;
  if p_video_order <> current_order then raise exception 'submission must target the first unanswered queue order'; end if;
  perform public.submit_video_response(p_participant_id, p_session_number, p_video_id, p_video_order, p_answer, p_response_time_ms, p_no_response_latency_ms, p_video_completed, p_clicks);
end
$$;

revoke all on function public.start_or_resume_assessment(text, integer, text) from public, authenticated;
grant execute on function public.start_or_resume_assessment(text, integer, text) to anon;
revoke all on function public.submit_video_response(text, integer, text, integer, boolean, bigint, bigint, boolean, jsonb, text) from public, authenticated;
grant execute on function public.submit_video_response(text, integer, text, integer, boolean, bigint, bigint, boolean, jsonb, text) to anon;
