create extension if not exists pgcrypto;

create table if not exists public.videos (
  video_id text primary key,
  bucket text not null,
  file_path text not null,
  has_lesion boolean not null default false,
  lesion_onset_sec numeric(10, 3),
  is_test boolean not null default true,
  session_pool integer check (session_pool between 1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.videos
  add column if not exists has_lesion boolean not null default false,
  add column if not exists lesion_onset_sec numeric(10, 3),
  add column if not exists is_test boolean not null default true,
  add column if not exists session_pool integer;

create index if not exists videos_study_mode_pool_idx
  on public.videos (is_test, session_pool, video_id);

create table if not exists public.assessment_queue (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_number integer not null check (session_number between 1 and 3),
  video_id text not null references public.videos (video_id),
  video_order integer not null check (video_order >= 1),
  created_at timestamptz not null default now()
);

create unique index if not exists assessment_queue_session_order_idx
  on public.assessment_queue (participant_id, session_number, video_order);

create unique index if not exists assessment_queue_session_video_idx
  on public.assessment_queue (participant_id, session_number, video_id);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_number integer not null check (session_number between 1 and 3),
  video_id text not null references public.videos (video_id),
  video_order integer not null check (video_order >= 1),
  answer text not null check (answer in ('yes', 'no')),
  correct boolean not null,
  response_type text not null check (
    response_type in ('lesion_detected', 'no_lesion_detected')
  ),
  response_time_ms integer not null check (response_time_ms >= 0),
  video_time_at_click numeric(10, 3),
  detection_latency_ms integer,
  video_completed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.responses
  add column if not exists participant_id text,
  add column if not exists session_number integer,
  add column if not exists video_order integer,
  add column if not exists correct boolean,
  add column if not exists response_type text,
  add column if not exists video_time_at_click numeric(10, 3),
  add column if not exists detection_latency_ms integer,
  add column if not exists video_completed boolean not null default false;

create index if not exists responses_participant_session_order_idx
  on public.responses (participant_id, session_number, video_order);

create unique index if not exists responses_unique_trial
  on public.responses (participant_id, session_number, video_id, video_order);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'assessment_queue_session_number_range'
  ) then
    alter table public.assessment_queue
      add constraint assessment_queue_session_number_range
      check (session_number between 1 and 3)
      not valid;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'responses_session_number_range'
  ) then
    alter table public.responses
      add constraint responses_session_number_range
      check (session_number between 1 and 3)
      not valid;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'videos_session_pool_range'
  ) then
    alter table public.videos
      add constraint videos_session_pool_range
      check (session_pool is null or session_pool between 1 and 3)
      not valid;
  end if;
end $$;

alter table public.videos enable row level security;
alter table public.assessment_queue enable row level security;
alter table public.responses enable row level security;

drop policy if exists "Allow anonymous V001 video lookup"
  on public.videos;

drop policy if exists "Allow anonymous videos lookup"
  on public.videos;

create policy "Allow anonymous videos lookup"
  on public.videos
  for select
  to anon
  using (true);

drop policy if exists "Allow anonymous assessment queue lookup"
  on public.assessment_queue;

create policy "Allow anonymous assessment queue lookup"
  on public.assessment_queue
  for select
  to anon
  using (true);

drop policy if exists "Allow anonymous assessment queue inserts"
  on public.assessment_queue;

create policy "Allow anonymous assessment queue inserts"
  on public.assessment_queue
  for insert
  to anon
  with check (
    length(trim(participant_id)) > 0
    and session_number between 1 and 3
    and video_order >= 1
    and exists (
      select 1
      from public.videos v
      where v.video_id = public.assessment_queue.video_id
    )
  );

drop policy if exists "Allow anonymous response inserts"
  on public.responses;

create policy "Allow anonymous response inserts"
  on public.responses
  for insert
  to anon
  with check (
    length(trim(participant_id)) > 0
    and session_number between 1 and 3
    and video_order >= 1
    and answer in ('yes', 'no')
    and correct is not null
    and response_type in ('lesion_detected', 'no_lesion_detected')
    and response_time_ms >= 0
    and video_time_at_click is not null
    and video_time_at_click >= 0
    and video_completed is not null
    and exists (
      select 1
      from public.videos v
      where v.video_id = public.responses.video_id
    )
  );

create or replace function public.get_next_video_order(
  p_participant_id text,
  p_session_number integer
)
returns integer
language sql
security definer
set search_path = public
as $$
  with queued as (
    select q.video_id, q.video_order
    from public.assessment_queue q
    where q.participant_id = p_participant_id
      and q.session_number = p_session_number
  )
  select coalesce(
    (
      select min(q.video_order)
      from queued q
      where not exists (
        select 1
        from public.responses r
        where r.participant_id = p_participant_id
          and r.session_number = p_session_number
          and r.video_id = q.video_id
          and r.video_order = q.video_order
      )
    ),
    (
      select count(*)::integer + 1
      from queued
    )
  );
$$;

grant execute on function public.get_next_video_order(text, integer) to anon;

insert into storage.buckets (id, name, public)
values ('SSL', 'SSL', false)
on conflict (id) do update set public = false;

drop policy if exists "Allow anonymous V001 signed URL reads"
  on storage.objects;

drop policy if exists "Allow anonymous V001 video reads"
  on storage.objects;

drop policy if exists "Allow anonymous signed URL reads for video objects"
  on storage.objects;

create policy "Allow anonymous signed URL reads for video objects"
  on storage.objects
  for select
  to anon
  using (
    bucket_id = 'SSL'
    and exists (
      select 1
      from public.videos v
      where v.bucket = storage.objects.bucket_id
        and v.file_path = storage.objects.name
    )
  );
