create extension if not exists pgcrypto;

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  video_id text not null,
  bucket text not null,
  file_path text not null,
  has_lesion boolean not null default false,
  lesion_onset_sec numeric(10, 3),
  is_test boolean not null default true,
  session_pool integer check (session_pool between 1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.videos
  add column if not exists has_lesion boolean not null default false,
  add column if not exists lesion_onset_sec numeric(10, 3),
  add column if not exists is_test boolean not null default true,
  add column if not exists session_pool integer;

create unique index if not exists videos_video_id_key
  on public.videos (video_id);

create index if not exists videos_study_mode_pool_idx
  on public.videos (is_test, session_pool, video_id);

create table if not exists public.assessment_queue (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_number integer not null check (session_number between 1 and 3),
  video_id text not null references public.videos (video_id),
  video_order integer not null check (video_order >= 1),
  created_at timestamptz not null default now()
);

create unique index if not exists assessment_queue_session_order_idx
  on public.assessment_queue (participant_id, session_number, video_order);

create unique index if not exists assessment_queue_session_video_idx
  on public.assessment_queue (participant_id, session_number, video_id);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_number integer not null check (session_number between 1 and 3),
  video_id text not null references public.videos (video_id),
  video_order integer not null check (video_order >= 1),
  answer boolean not null,
  correct boolean not null,
  response_type text not null check (
    response_type in ('lesion_detected', 'no_lesion_detected')
  ),
  response_time_ms integer not null check (response_time_ms >= 0),
  video_time_at_click numeric(10, 3),
  detection_latency_ms integer,
  video_completed boolean not null default false,
  no_response_latency_ms bigint check (
    no_response_latency_ms is null
    or no_response_latency_ms >= 0
  ),
  created_at timestamptz not null default now()
);

alter table public.responses
  add column if not exists participant_id text,
  add column if not exists session_number integer,
  add column if not exists video_order integer,
  add column if not exists correct boolean,
  add column if not exists response_type text,
  add column if not exists video_time_at_click numeric(10, 3),
  add column if not exists detection_latency_ms integer,
  add column if not exists video_completed boolean not null default false,
  add column if not exists no_response_latency_ms bigint;

create index if not exists responses_participant_session_order_idx
  on public.responses (participant_id, session_number, video_order);

create unique index if not exists responses_unique_trial
  on public.responses (participant_id, session_number, video_id, video_order);

create table if not exists public.lesion_detection_events (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_number integer not null
    check (session_number between 1 and 3),
  video_id text not null references public.videos (video_id),
  video_order integer not null check (video_order >= 1),
  click_index integer not null check (click_index >= 1),
  video_time_at_click double precision not null
    check (video_time_at_click >= 0),
  response_time_ms bigint not null check (response_time_ms >= 0),
  lesion_onset_sec double precision,
  detection_latency_ms bigint,
  overridden boolean not null,
  final_valid boolean not null,
  created_at timestamptz not null default now(),
  constraint lesion_detection_events_unique_click
    unique (participant_id, session_number, video_id, click_index),
  constraint lesion_detection_events_validity_pair
    check (final_valid <> overridden)
);

create index if not exists lesion_detection_events_audit_order_idx
  on public.lesion_detection_events (
    participant_id,
    session_number,
    video_order,
    click_index
  );

create index if not exists lesion_detection_events_final_analysis_idx
  on public.lesion_detection_events (
    video_id,
    detection_latency_ms
  )
  where final_valid = true;

alter table public.videos enable row level security;
alter table public.assessment_queue enable row level security;
alter table public.responses enable row level security;
alter table public.lesion_detection_events enable row level security;

drop policy if exists "Allow anonymous V001 video lookup"
  on public.videos;

drop policy if exists "Allow anonymous videos lookup"
  on public.videos;

create policy "Allow anonymous videos lookup"
  on public.videos
  for select
  to anon
  using (true);

drop policy if exists "Allow anonymous assessment queue lookup"
  on public.assessment_queue;

create policy "Allow anonymous assessment queue lookup"
  on public.assessment_queue
  for select
  to anon
  using (true);

drop policy if exists "Allow anonymous assessment queue inserts"
  on public.assessment_queue;

create policy "Allow anonymous assessment queue inserts"
  on public.assessment_queue
  for insert
  to anon
  with check (
    length(trim(participant_id)) > 0
    and session_number between 1 and 3
    and video_order >= 1
    and exists (
      select 1
      from public.videos v
      where v.video_id = public.assessment_queue.video_id
    )
  );

drop policy if exists "Allow anonymous response inserts"
  on public.responses;

drop policy if exists "Allow anonymous lesion event inserts"
  on public.lesion_detection_events;

-- Direct writes are revoked; only the trusted SECURITY DEFINER RPC may write.
revoke all on table public.lesion_detection_events
  from public, anon, authenticated;
revoke all on sequence public.lesion_detection_events_id_seq
  from public, anon, authenticated;
revoke all on table public.responses
  from public, anon, authenticated;
revoke all on sequence public.responses_id_seq
  from public, anon, authenticated;

create or replace function public.get_next_video_order(
  p_participant_id text,
  p_session_number integer
)
returns integer
language sql
security definer
set search_path = public
as $$
  with queued as (
    select q.video_id, q.video_order
    from public.assessment_queue q
    where q.participant_id = p_participant_id
      and q.session_number = p_session_number
  )
  select coalesce(
    (
      select min(q.video_order)
      from queued q
      where not exists (
        select 1
        from public.responses r
        where r.participant_id = p_participant_id
          and r.session_number = p_session_number
          and r.video_id = q.video_id
          and r.video_order = q.video_order
      )
    ),
    (
      select count(*)::integer + 1
      from queued
    )
  );
$$;

grant execute on function public.get_next_video_order(text, integer) to anon;

-- The trusted migration owner, not anon, performs the validated table writes.
create or replace function public.submit_video_response(
  p_participant_id text,
  p_session_number integer,
  p_video_id text,
  p_video_order integer,
  p_answer boolean,
  p_response_time_ms bigint,
  p_no_response_latency_ms bigint,
  p_video_completed boolean,
  p_clicks jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  video_has_lesion boolean;
  video_lesion_onset_sec double precision;
  click_count integer;
  distinct_click_count integer;
  minimum_click_index integer;
  maximum_click_index integer;
  first_video_time double precision;
  first_response_time_ms bigint;
  first_detection_latency_ms bigint;
begin
  if pg_catalog.length(pg_catalog.btrim(pg_catalog.coalesce(p_participant_id, ''))) = 0 then
    raise exception 'participant_id is required';
  end if;

  if p_session_number is null
     or p_session_number not between 1 and 3 then
    raise exception 'session_number must be 1, 2, or 3';
  end if;

  if p_video_order is null or p_video_order < 1 then
    raise exception 'video_order must be positive';
  end if;

  if p_answer is null then
    raise exception 'answer is required';
  end if;

  if p_video_completed is distinct from true then
    raise exception 'video must be completed before submission';
  end if;

  if p_response_time_ms is null or p_response_time_ms < 0 then
    raise exception 'response_time_ms must be non-negative';
  end if;

  if p_answer is true and p_no_response_latency_ms is not null then
    raise exception 'positive responses cannot have no_response_latency_ms';
  end if;

  if p_answer is false and (
    p_no_response_latency_ms is null
    or p_no_response_latency_ms < 0
  ) then
    raise exception 'negative responses require no_response_latency_ms';
  end if;

  if p_clicks is null or pg_catalog.jsonb_typeof(p_clicks) <> 'array' then
    raise exception 'p_clicks must be a JSON array';
  end if;

  select v.has_lesion, v.lesion_onset_sec
  into video_has_lesion, video_lesion_onset_sec
  from public.assessment_queue q
  join public.videos v on v.video_id = q.video_id
  where q.participant_id = p_participant_id
    and q.session_number = p_session_number
    and q.video_id = p_video_id
    and q.video_order = p_video_order;

  if not found then
    raise exception 'assessment queue item does not exist';
  end if;

  if video_has_lesion is null then
    raise exception 'videos.has_lesion is required';
  end if;

  select
    pg_catalog.count(*)::integer,
    pg_catalog.count(distinct click_row.click_index)::integer,
    pg_catalog.min(click_row.click_index),
    pg_catalog.max(click_row.click_index)
  into
    click_count,
    distinct_click_count,
    minimum_click_index,
    maximum_click_index
  from pg_catalog.jsonb_to_recordset(p_clicks) as click_row(
    click_index integer,
    video_time_at_click double precision,
    response_time_ms bigint
  );

  if p_answer is true and click_count = 0 then
    raise exception 'positive responses require at least one lesion click';
  end if;

  if click_count > 0 and (
    distinct_click_count <> click_count
    or minimum_click_index <> 1
    or maximum_click_index <> click_count
  ) then
    raise exception 'click indexes must be unique and contiguous from 1';
  end if;

  if exists (
    select 1
    from pg_catalog.jsonb_to_recordset(p_clicks) as click_row(
      click_index integer,
      video_time_at_click double precision,
      response_time_ms bigint
    )
    where click_row.click_index is null
      or click_row.video_time_at_click is null
      or click_row.video_time_at_click < 0
      or click_row.response_time_ms is null
      or click_row.response_time_ms < 0
  ) then
    raise exception 'click timing values are invalid';
  end if;

  if p_answer is true then
    select
      pg_catalog.round(click_row.video_time_at_click::numeric, 3)::double precision,
      click_row.response_time_ms,
      case
        when video_lesion_onset_sec is null then null
        else pg_catalog.round(
          (
            pg_catalog.round(click_row.video_time_at_click::numeric, 3)::double precision
            - video_lesion_onset_sec
          ) * 1000
        )::bigint
      end
    into
      first_video_time,
      first_response_time_ms,
      first_detection_latency_ms
    from pg_catalog.jsonb_to_recordset(p_clicks) as click_row(
      click_index integer,
      video_time_at_click double precision,
      response_time_ms bigint
    )
    order by click_row.click_index
    limit 1;
  end if;

  insert into public.lesion_detection_events (
    participant_id,
    session_number,
    video_id,
    video_order,
    click_index,
    video_time_at_click,
    response_time_ms,
    lesion_onset_sec,
    detection_latency_ms,
    overridden,
    final_valid
  )
  select
    p_participant_id,
    p_session_number,
    p_video_id,
    p_video_order,
    click_row.click_index,
    pg_catalog.round(click_row.video_time_at_click::numeric, 3)::double precision,
    click_row.response_time_ms,
    video_lesion_onset_sec,
    case
      when video_lesion_onset_sec is null then null
      else pg_catalog.round(
        (
          pg_catalog.round(click_row.video_time_at_click::numeric, 3)::double precision
          - video_lesion_onset_sec
        ) * 1000
      )::bigint
    end,
    not p_answer,
    p_answer
  from pg_catalog.jsonb_to_recordset(p_clicks) as click_row(
    click_index integer,
    video_time_at_click double precision,
    response_time_ms bigint
  );

  insert into public.responses (
    participant_id,
    session_number,
    video_id,
    video_order,
    answer,
    correct,
    response_time_ms,
    video_time_at_click,
    detection_latency_ms,
    response_type,
    video_completed,
    no_response_latency_ms
  )
  values (
    p_participant_id,
    p_session_number,
    p_video_id,
    p_video_order,
    p_answer,
    video_has_lesion = p_answer,
    case
      when p_answer then first_response_time_ms
      else p_response_time_ms
    end,
    case when p_answer then first_video_time else null end,
    case when p_answer then first_detection_latency_ms else null end,
    case
      when p_answer then 'lesion_detected'
      else 'no_lesion_detected'
    end,
    true,
    case when p_answer then null else p_no_response_latency_ms end
  );
end
$$;

revoke all on function public.submit_video_response(
  text,
  integer,
  text,
  integer,
  boolean,
  bigint,
  bigint,
  boolean,
  jsonb
) from public;

revoke all on function public.submit_video_response(
  text,
  integer,
  text,
  integer,
  boolean,
  bigint,
  bigint,
  boolean,
  jsonb
) from authenticated;

grant execute on function public.submit_video_response(
  text,
  integer,
  text,
  integer,
  boolean,
  bigint,
  bigint,
  boolean,
  jsonb
) to anon;

comment on function public.submit_video_response(
  text,
  integer,
  text,
  integer,
  boolean,
  bigint,
  bigint,
  boolean,
  jsonb
) is 'SECURITY DEFINER is intentional: response and event tables revoke direct public, anon, and authenticated writes so this validated RPC is the only write boundary.';

insert into storage.buckets (id, name, public)
values ('SSL', 'SSL', false)
on conflict (id) do update set public = false;

drop policy if exists "Allow anonymous V001 signed URL reads"
  on storage.objects;

drop policy if exists "Allow anonymous V001 video reads"
  on storage.objects;

drop policy if exists "Allow anonymous signed URL reads for video objects"
  on storage.objects;

create policy "Allow anonymous signed URL reads for video objects"
  on storage.objects
  for select
  to anon
  using (
    bucket_id = 'SSL'
    and exists (
      select 1
      from public.videos v
      where v.bucket = storage.objects.bucket_id
        and v.file_path = storage.objects.name
    )
  );
